### ISSUE TITLE
可否给出使用用例

### ISSUE THREAD

**Issue by CoderYellow** [hadesy/gitlab-license#1]
请教license格式是怎样的，gitlab公钥怎么替换

**Comment by hadesy** [comment]
公钥位置位于embedded/service/gitlab-rails/.license_encryption_key.pub
license形如：
`
Array
(
    [version] => 1
    [licensee] => Array
        (
            [Name] => xxxxx
            [Email] => xxxxx
            [Company] => xxxxx
        )
    [issued_at] => 2018-11-11
    [expires_at] => 2020-11-11
    [notify_admins_at] => 2020-11-10
    [notify_users_at] => 2020-11-10
    [restrictions] => Array
        (
            [id] => 100xx
            [previous_user_count] => 
            [trueup_quantity] => 
            [trueup_from] => 
            [trueup_to] => 
            [active_user_count] => 100
            [add_ons] => Array
                ()
            [subscription_id] => 
            [plan] => ultimate
            [trial] => 1
        )
)
`

**Comment by Taki-Kun** [comment]
@hadesy 请问在ee中哪段代码对license做了decrypt？

**Comment by gclm** [comment]
你好，请问有没有更详细的使用教程，不知道这个自己的私钥和公钥指的是什么，

**Comment by chenzixia** [comment]
代码中的公钥没有匹配的私钥，修改了时间调用加密方法的时候会报错，请问题如何处理

是需要将GITLAB中的公钥替换掉吗 YOUR_PUBLIC_KEY   YOUR_PRIVATE_KEY 这两个是要自己弄吗

const GITLAB_PUBLIC_KEY = '-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0Hxv3MkkZbMrKtIs6np9
ccP4OwGBkNhIvhPjcQP48hbbascv5RqsOquQGrYSD2ZrE/kbkRdkIcoHEeTZLif+
bDKFZFI7o5x0H92o9/GSvxHJhQ8mkmvwxD7lssGShwZEm8WG+U7BZqUV/gGmCDqe
9W8H8Fq2B0ck8IXjbQ4Zz+JlyV/NHZTZcs69plFiLKh4N6GYVftOVwSomh0bbypP
OB9WnLC7RC9a2LRrhtf8sqa2rRFmtyMMfgFFzLMzS+w+1K4+QLnWP1gKQVzaFnzk
pnwKPrqbGFYbRztIVEWbs8jPYlLkGb8ME4C84YVtQgbQcbyisU/VW3wUGkhT+J0k
xwIDAQAB
-----END PUBLIC KEY-----';
    const YOUR_PUBLIC_KEY = '----';
    const YOUR_PRIVATE_KEY = '----';

**Comment by hadesy** [comment]
Updated.
