### ISSUE TITLE
error！  How to solve it？

### ISSUE THREAD

**Issue by xieninghong** [hadesy/gitlab-license#2]
Whoops, something went wrong on our end.
Try refreshing the page, or going back and attempting the action again.

Please contact your GitLab administrator if this problem persists.

**Comment by hadesy** [comment]
`gitlab-ctl tail`

**Comment by xieninghong** [comment]
> `gitlab-ctl tail`

==> /var/log/gitlab/gitlab-rails/production.log <==
Started POST "/admin/license" for 127.0.0.1 at 2019-03-14 10:34:19 +0800
Processing by Admin::LicensesController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"[FILTERED]", "license_type"=>"key", "license"=>{"data"=>"eyJkYXRhIjoiY1ZBTVBmcWYyXC9OdG01S25CRXk3XC9xTEJ3NW1WUW5rN1VRS2p1Z2k5VTUxbzJCbE9iV2JNU1hmc3g1VUpWRkk4eVE0MjV6ekpkaVg0N0xrWDU4TkdwME5TOFpYKzZnSmtsUnBHeFpJTHdLRWxHcERQWW1LcitVUEYyQVEwcnkrT1RhZmdLWkFpVm91ZkxoYnN5Ym9MMVIwRkplbzBzb0srVVdwcmhFVzgrZ1hrNUxSb1lmV3FjV2wzc1lnaG5WVjE0VERLTVdmRFFheU1Db3BsWVFhbnowZTRsbUg4Y3k4MVhRZG9YUUtYWUlhZ2l4b0ZpVUFcL3NRbVlUN1ZcL2JRU201NmRuVExMeHdFK2EzMmJFN0JXZjBrSG9IczJqbFlcL0RpdmR1ajJyYndWa1RuSXhFMXRmQXd2bmc2RERRS0JOZzNMMk4yMlk2ZEgzK1Nhd2RYNitQOEFXeXdNUE9HQUVvMFwvSGF6U1BNVmlvRFJnUlJqS0MweVJ0Q1ZRVTRMZ3JjT2xcLzRMQnl0SUhLd1FobVljVnpFT1hmTk5ja2NydVNcL3VkMk53WWlEdXlHWVMxUCthd0ZGNTU5U3F0Rmdwb1FsV2xPMkFnaTFMaGswREFwRFEwelAwTE1Nb3NqSHZsZHNxSXFQb3FzR2JXV2hlR0tDeGRLMkh5MzZZNTczQkpZUjdaR05YemduRGZadFIrbVlFamVnTnVHWHNITFYyWURzXC9ibXZ2WFBKUEhRPSIsImtleSI6ImRPM1ZCenZnQmZJUzM4dkdEZkI3aTlVb0N2WkhsdlNPMU1HVm9NUEdVYis3d0JmT0oxa1E2dGV3MDVEcnlZMjFqRXJNRUdRUEZrRHhBSitQa2I0c3kzVTBmbGFyZ1ZZYmZWTDY4THZOd29BMEQyUHdYXC9jcnZUV201VkQxQWE5Q3liVlwvTGpqWDN2amVaOTJGTCtuY3NtOXdLODEyRStBYzNKRkswbW45cEJTUkppSHlTS2lndnBPM2I1ZXhSc2N0cWdsQTlYWWNJQm9FNUdTaTZtaUhLM0dZXC9uYUhqWW1lQnNtWHNPcjFzdzNyWjJTeTRETXR0REhzcE45SGFUYzlYWVlSK0xkSzVIVWVHcUlJbE4xTmdXYWZ5dXY3UFkyY2EybTNnWEpScmJtdElMeGJuMGJnRHNMVDh3Kzk3ODZjUU1ja0gzVDBJOWlhcllRdkc2cHhFdz09IiwiaXYiOiJDak90UUx4UDExSkJpd015Umt4U2tnPT0ifQ=="}}
Completed 500 Internal Server Error in 26ms (ActiveRecord: 2.0ms | Elasticsearch: 0.0ms)
  
ArgumentError (key must be 16 bytes):
  
ee/app/models/license.rb:260:in `license'
ee/app/models/license.rb:267:in `license?'
ee/app/models/license.rb:394:in `valid_license'
ee/app/controllers/admin/licenses_controller.rb:37:in `block in create'
ee/app/controllers/admin/licenses_controller.rb:36:in `create'
lib/gitlab/i18n.rb:55:in `with_locale'
lib/gitlab/i18n.rb:61:in `with_user_locale'
app/controllers/application_controller.rb:428:in `set_locale'
lib/gitlab/middleware/multipart.rb:103:in `call'
lib/gitlab/request_profiler/middleware.rb:16:in `call'
ee/lib/gitlab/jira/middleware.rb:15:in `call'
lib/gitlab/middleware/go.rb:19:in `call'
lib/gitlab/etag_caching/middleware.rb:13:in `call'
lib/gitlab/middleware/correlation_id.rb:16:in `block in call'
lib/gitlab/correlation_id.rb:15:in `use_id'
lib/gitlab/middleware/correlation_id.rb:15:in `call'
lib/gitlab/middleware/rails_queue_duration.rb:24:in `call'
lib/gitlab/metrics/rack_middleware.rb:17:in `block in call'
lib/gitlab/metrics/transaction.rb:55:in `run'
lib/gitlab/metrics/rack_middleware.rb:17:in `call'
lib/gitlab/middleware/read_only/controller.rb:42:in `call'
lib/gitlab/middleware/read_only.rb:18:in `call'
lib/gitlab/middleware/basic_health_check.rb:25:in `call'
lib/gitlab/request_context.rb:20:in `call'
lib/gitlab/metrics/requests_rack_middleware.rb:29:in `call'
lib/gitlab/middleware/release_env.rb:13:in `call'

==> /var/log/gitlab/gitlab-rails/production_json.log <==
{"method":"POST","path":"/admin/license","format":"html","controller":"Admin::LicensesController","action":"create","status":500,"error":"ArgumentError: key must be 16 bytes","duration":27.8,"view":0.0,"db":2.05,"time":"2019-03-14T02:34:19.245Z","params":[{"key":"utf8","value":"✓"},{"key":"authenticity_token","value":"[FILTERED]"},{"key":"license_type","value":"key"},{"key":"license","value":{"data":"eyJkYXRhIjoiY1ZBTVBmcWYyXC9OdG01S25CRXk3XC9xTEJ3NW1WUW5rN1VRS2p1Z2k5VTUxbzJCbE9iV2JNU1hmc3g1VUpWRkk4eVE0MjV6ekpkaVg0N0xrWDU4TkdwME5TOFpYKzZnSmtsUnBHeFpJTHdLRWxHcERQWW1LcitVUEYyQVEwcnkrT1RhZmdLWkFpVm91ZkxoYnN5Ym9MMVIwRkplbzBzb0srVVdwcmhFVzgrZ1hrNUxSb1lmV3FjV2wzc1lnaG5WVjE0VERLTVdmRFFheU1Db3BsWVFhbnowZTRsbUg4Y3k4MVhRZG9YUUtYWUlhZ2l4b0ZpVUFcL3NRbVlUN1ZcL2JRU201NmRuVExMeHdFK2EzMmJFN0JXZjBrSG9IczJqbFlcL0RpdmR1ajJyYndWa1RuSXhFMXRmQXd2bmc2RERRS0JOZzNMMk4yMlk2ZEgzK1Nhd2RYNitQOEFXeXdNUE9HQUVvMFwvSGF6U1BNVmlvRFJnUlJqS0MweVJ0Q1ZRVTRMZ3JjT2xcLzRMQnl0SUhLd1FobVljVnpFT1hmTk5ja2NydVNcL3VkMk53WWlEdXlHWVMxUCthd0ZGNTU5U3F0Rmdwb1FsV2xPMkFnaTFMaGswREFwRFEwelAwTE1Nb3NqSHZsZHNxSXFQb3FzR2JXV2hlR0tDeGRLMkh5MzZZNTczQkpZUjdaR05YemduRGZadFIrbVlFamVnTnVHWHNITFYyWURzXC9ibXZ2WFBKUEhRPSIsImtleSI6ImRPM1ZCenZnQmZJUzM4dkdEZkI3aTlVb0N2WkhsdlNPMU1HVm9NUEdVYis3d0JmT0oxa1E2dGV3MDVEcnlZMjFqRXJNRUdRUEZrRHhBSitQa2I0c3kzVTBmbGFyZ1ZZYmZWTDY4THZOd29BMEQyUHdYXC9jcnZUV201VkQxQWE5Q3liVlwvTGpqWDN2amVaOTJGTCtuY3NtOXdLODEyRStBYzNKRkswbW45cEJTUkppSHlTS2lndnBPM2I1ZXhSc2N0cWdsQTlYWWNJQm9FNUdTaTZtaUhLM0dZXC9uYUhqWW1lQnNtWHNPcjFzdzNyWjJTeTRETXR0REhzcE45SGFUYzlYWVlSK0xkSzVIVWVHcUlJbE4xTmdXYWZ5dXY3UFkyY2EybTNnWEpScmJtdElMeGJuMGJnRHNMVDh3Kzk3ODZjUU1ja0gzVDBJOWlhcllRdkc2cHhFdz09IiwiaXYiOiJDak90UUx4UDExSkJpd015Umt4U2tnPT0ifQ=="}}],"remote_ip":"192.168.90.1","user_id":1,"username":"root","ua":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36","correlation_id":"leufkmMVqd7"}

==> /var/log/gitlab/nginx/gitlab_access.log <==
192.168.90.1 - - [14/Mar/2019:10:34:19 +0800] "POST /admin/license HTTP/1.1" 500 2926 "http://192.168.90.6/admin/license/new" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36"

==> /var/log/gitlab/gitlab-workhorse/current <==
2019-03-14_02:34:19.27980 192.168.90.6 127.0.0.1:0 - - [2019/03/14:10:34:19 +0800] "POST /admin/license HTTP/1.1" 500 2926 "http://192.168.90.6/admin/license/new" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36" 0.050

**Comment by hadesy** [comment]
Fixed
